services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    networks:
      - original-starter

  postgres:
    image: postgres:16
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - original-starter

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - '8080:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - original-starter

volumes:
  postgres-data:
  pgadmin-data:

networks:
  original-starter:
