# node 
FROM node:20-alpine3.21

# set working directory
WORKDIR /app

COPY package*.json /app
# install dependencies

RUN npm ci

COPY . .

# build
RUN npm run build

# expose port
EXPOSE 5000

# start
CMD [ "npm", "run", "start:prod" ]