# node 
FROM node:20-alpine3.21

# set working directory
WORKDIR /app

COPY package*.json /app
# install dependencies

RUN npm install -g npm@11.4.2

RUN npm install --legacy-peer-deps 

#  Copy 
COPY . /app
COPY .env /app/.env
# install nest js silent
RUN npm install -g @nestjs/cli --silent

# build
RUN npm run build

# expose port
EXPOSE 5000

# start
CMD [ "npm", "run", "start:prod" ]